name: Laravel & React CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: nationsoundstest
        ports:
          - 3307:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, bcmath, curl, dom, fileinfo, json, mysql, pdo, tokenizer

    - name: Copier le fichier .env.ci en .env
      run: cp .env.ci ./backend/.env
      working-directory: ./

    - name: Attendre que MySQL soit prêt
      run: sleep 30  # Attendre 30 secondes pour que MySQL soit prêt

    - name: Vérifier la disponibilité de MySQL
      run: mysqladmin -h mysql -u root ping

    - name: Installer les dépendances Composer
      run: composer install --prefer-dist --no-progress
      working-directory: ./backend

    - name: Configurer la base de données
      run: php artisan key:generate && php artisan migrate --no-interaction --force
      working-directory: ./backend

    - name: Exécuter les tests unitaires Laravel
      run: php artisan test
      working-directory: ./backend

    - name: Afficher les logs du conteneur MySQL
      if: failure()
      run: docker logs $(docker ps -q --filter "ancestor=mysql:5.7")
