name: Laravel & React CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: nationsoundsdevelopment
        ports:
          - 3307:3306  # Port mapping changed to avoid conflicts
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, bcmath, curl, dom, fileinfo, json, mysql, pdo, tokenizer

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Copy .env.example to .env
      run: cp .env.example .env

    - name: Set up database
      run: |
        php artisan key:generate
        php artisan migrate --no-interaction --force

    - name: Run Laravel unit tests
      run: php artisan test

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.11.1'

    - name: Install Node.js dependencies
      run: npm install

    - name: Run React tests
      run: npm test -- --watchAll=false

    - name: Build React app
      run: npm run build

    - name: Run Lighthouse performance tests
      run: npx lhci autorun

    - name: Run security analysis
      run: |
        composer require --dev enlightn/security-checker
        php artisan security:check

    - name: Get MySQL container logs
      if: failure()
      run: docker logs $(docker ps -q --filter "ancestor=mysql:5.7")
