name: Laravel & React CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: nationsoundsdevelopment
        ports:
          - 3307:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, bcmath, curl, dom, fileinfo, json, mysql, pdo, tokenizer

    - name: Vérifier l'existence du fichier .env
      run: ls -la ./backend/.env

    - name: Attendre que MySQL soit prêt
      run: sleep 20  # Attendre 20 secondes pour que MySQL soit prêt

    - name: Installer les dépendances Composer
      run: composer install --prefer-dist --no-progress
      working-directory: ./backend

    - name: Configurer la base de données
      run: php artisan key:generate && php artisan migrate --no-interaction --force
      working-directory: ./backend

    - name: Exécuter les tests unitaires Laravel
      run: php artisan test
      working-directory: ./backend

    - name: Configurer Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.11.1'

    - name: Installer les dépendances Node.js
      run: npm install
      working-directory: ./backend

    - name: Exécuter les tests React
      run: npm test -- --watchAll=false
      working-directory: ./backend

    - name: Compiler l'application React
      run: npm run build
      working-directory: ./backend

    - name: Exécuter les tests de performance Lighthouse
      run: npx lhci autorun
      working-directory: ./backend

    - name: Exécuter l'analyse de sécurité
      run: composer require --dev enlightn/security-checker && php artisan security:check
      working-directory: ./backend

    - name: Afficher les logs du conteneur MySQL
      if: failure()
      run: docker logs $(docker ps -q --filter "ancestor=mysql:5.7")
